### ISSUE TITLE
색상 선택기능 수정

### ISSUE THREAD

**Issue by Dr-robin** [wlzla000/CentrePolis#1]
지금 색상 선택하는 기능을 JSColor 라이브러리로 처리하는것 같은데 input type="color"를 써볼 생각은 없음?

**Comment by Dr-robin** [comment]
아 생각해보니 여기 html은 예제였지 ㅁㄴㅇㄹ

**Comment by wlzla000** [comment]
첨에는 IE 고려해서 input[type="color"] 말고 JSColor 쓴 건데 나중에야 IE가 Web Audio API 지원 안 한다는 거 알았음.. ㅠㅠ
JSColor의 색상 선택 기능 말고도 다른 JSColor의 기능도 쓰고 있어서
input[type="color"]로 바꾸려면 조금 시간이 걸리기도 하고
게다가 이건 그냥 예제라서 대충 짠 감이 있음. 자바스크립트도 좀 더럽게 짰음 ㅋㅋ

At first, I used JSColor library instead of input[type="color"] because I considered IE.
But in fact, IE does not support the Web Audio API!

Now I want to use input[type="color"],
but I'm using not only JSColor color picking feature but also JSColor's another features.
So to fix it, I have to take time to do so.
And since it's just an example file, I think that I don't have to put a lot of effort into it.

**Comment by wlzla000** [comment]
GitHub은 다른 사람이 소스 코드 수정할 수도 있음?
Do other people can modify my codes on GitHub?

**Comment by Dr-robin** [comment]
포크 뜬 다음에 Pull Request 넣어서 합칠 수는 있지
모르는 사람이 직접 소스 수정은 안됨
